---
abstract: 'Utility functions for checking references'
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1, CPAN::Meta::Converter version 2.142690'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Ref-Util
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: '5.57'
  Test::More: '0'
resources:
  bugtracker: https://github.com/p5pclub/ref-util/issues
  repository: https://github.com/p5pclub/ref-util.git
version: '0.020'
